#!/bin/bash

export LC_ALL=C
file=$1

( [ -f "$file" ] && cat ${file} || cat ) |\
awk '{print $1 "_" $2, $3,$4 }' | sort | awk '
	BEGIN{ old=-999999; }
	{
		if (NF>=1){
			if ($1 == old) print 
			else {print ""; print ; old=$1 }
		} else { old=-999999 }
	}' | tr '_' ' ' |\
awk 'BEGIN{
	u[1]=0;  u[2]=0; 
	u2[1]=0; u2[2]=0; 
	n=0; sw=0;
}{
	if (NF >= 4 ){
		x=$1; y=$2;
		if (NF >= 5) w=$5
		else w=1
		u[1]+=$3 * w
		u[2]+=$4 * w
		u2[1]+=$3 * $3 * w
		u2[2]+=$4 * $4 * w
		n++
		sw+=w
	} else if (sw>0 && n>0) {
		a1=u[1]/sw
		a2=u[2]/sw
		sem1=sqrt ( (u2[1]/sw - (u[1]/sw)**2)/n )
		sem2=sqrt ( (u2[2]/sw - (u[2]/sw)**2)/n )
		
		print x,y,a1,a2,n,sem1,sem2

		u[1]=0;  u[2]=0; 
		u2[1]=0; u2[2]=0; 
		n=0; sw=0;
	}
}END{
	if (sw>0 && n>0) {
		a1=u[1]/sw
		a2=u[2]/sw
		sem1=sqrt ( (u2[1]/sw - (u[1]/sw)**2)/n )
		sem2=sqrt ( (u2[2]/sw - (u[2]/sw)**2)/n )
		
		print x,y,a1,a2,n,sem1,sem2
	}
}'


